# Generated by Django 6.0 on 2025-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('input_path', models.TextField()),
                ('output_path', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, default='spa', max_length=64)),
                ('optimize', models.IntegerField(default=2)),
                ('deskew', models.BooleanField(default=True)),
                ('rotate_pages', models.BooleanField(default=True)),
                ('force_ocr', models.BooleanField(default=False)),
            ],
        ),
    ]
